version: "3"
services:
  api-server: 
    image: api-server
    restart: unless-stopped
    container_name: api-server
    ports: 
      - "5000:5000"
    networks:
      - replica-set
  
  mongo-primary: 
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    command: 'mongod --replSet replica-set'
    networks:
      replica-set:
  
  mongo-worker-1: 
    image: mongo:latest
    volumes:
      - mongo-data-1:/data/db
    ports:
      - 27018:27017
    command: 'mongod --replSet replica-set'
    networks:
      replica-set:

  mongo-worker-2: 
    image: mongo:latest
    volumes:
      - mongo-data-2:/data/db
    ports:
      - 27019:27017
    command: 'mongod --replSet replica-set'
    networks:
      replica-set:

networks:
  replica-set: 
    driver: bridge

volumes:
  mongo-keys: 
  mongo-data:
  mongo-data-1:
  mongo-data-2: