version: "3"
services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx-network  
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'" 

  certbot: 
    image: certbot/certbot 
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  api-server: 
    image: api-server
    restart: unless-stopped
    container_name: api-server
    ports: 
      - "5000:5000"
    networks:
      - replica-set
      - nginx-network
    depends_on:
      - nginx
  
  mongo-primary: 
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    command: 'mongod --replSet replica-set'
    networks:
      replica-set:
  
  mongo-worker-1: 
    image: mongo:latest
    volumes:
      - mongo-data-1:/data/db
    ports:
      - 27018:27017
    command: 'mongod --replSet replica-set'
    networks:
      replica-set:

  mongo-worker-2: 
    image: mongo:latest
    volumes:
      - mongo-data-2:/data/db
    ports:
      - 27019:27017
    command: 'mongod --replSet replica-set'
    networks:
      replica-set:

networks:
  nginx-network:
    driver: bridge
  replica-set: 
    driver: bridge

volumes:
  mongo-keys: 
  mongo-data:
  mongo-data-1:
  mongo-data-2: