version: "3"
services: 
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    networks:
      - nginx-network   
  api-server: 
    image: api-server
    restart: unless-stopped
    container_name: api-server
    ports: 
      - "5000:5000"
    networks:
      - replica-set
      - nginx-network
    depends_on:
      - nginx
  mongo-keys:
    image: depop/openssl-bats
    volumes:
      - mongo-keys:/mongo-conf
    command: 'bash -c "openssl rand -base64 741 > /mongo-conf/mongodb-keyfile; chmod 600 /mongo-conf/mongodb-keyfile; chown 999 /mongo-conf/mongodb-keyfile"'
  mongo-primary: 
    image: mongo:latest 
    volumes:
      - mongo-keys:/opt/keyfile
      - mongo-data:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27017:27017
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet replica-set'
    depends_on:
        - mongo-keys
    networks:
      replica-set:
  mongo-worker-1: 
    image: mongo:latest 
    volumes:
      - mongo-keys:/opt/keyfile
      - mongo-data-1:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27018:27017
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet replica-set'
    depends_on:
        - mongo-keys
    networks:
      replica-set:
  mongo-worker-2: 
    image: mongo:latest 
    volumes:
      - mongo-keys:/opt/keyfile
      - mongo-data-2:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27019:27017
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet replica-set'
    depends_on:
        - mongo-keys
    networks:
      replica-set:

networks:
  nginx-network:
    driver: bridge
  replica-set: 
    driver: bridge

volumes:
  mongo-keys: 
  mongo-data:
  mongo-data-1:
  mongo-data-2: