version: "3"
services: 
  react-app:
    image: react-app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - meltin-ice

  api-server: 
    image: api-server
    restart: unless-stoped
    env_file: ./server/config/${ENV}.env
    ports: 
      - "5000:5000"
    networks:
      - melting-ice
      - replica-set

  mongo-keys:
    image: depop/openssl-bats
    volumes:
      - mongo-keys:/mongo-conf
    command: 'bash -c "openssl rand -base64 741 > /mongo-conf/mongodb-keyfile; chmod 600 /mongo-conf/mongodb-keyfile; chown 999 /mongo-conf/mongodb-keyfile"'

  mongo-primary: 
    image: mongo:latest 
    volumes:
      - mongo-keys:/opt/keyfile
      - mongo-data:/data/db
    env_file: ./db/mongod.env
    ports:
      - 27017:27017
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet replica-set'
    depends_on:
        - mongo-keys
    networks:
      replica-set:

  mongo-worker-1: 
    image: mongo:latest 
    volumes:
      - mongo-keys:/opt/keyfile
      - mongo-data-1:/data/db
    env_file: ./db/mongod.env
    ports:
      - 27018:27017
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet replica-set'
    depends_on:
        - mongo-keys
    networks:
      replica-set:

  mongo-worker-2: 
    image: mongo:latest 
    volumes:
      - mongo-keys:/opt/keyfile
      - mongo-data-2:/data/db
    env_file: ./db/mongod.env
    ports:
      - 27019:27017
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet replica-set'
    depends_on:
        - mongo-keys
    networks:
      replica-set:

networks:
  melting-app:
    driver: bridge
  replica-set: 
    driver: bridge

volumes:
  mongo-keys: 
  mongo-data:
  mongo-data-1:
  mongo-data-2:
  caddy-data: 
    driver: local
  caddy-config: 
    driver: local
